name: API Testing with Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests - Valid Request
        run: newman run Restful-booker-collection.json --folder "Valid request" -e restful-booker-env.json -d restful-booker-data.csv

      - name: Run API Tests - Create Token
        run: newman run Restful-booker-collection.json --folder "Create token" -e restful-booker-env.json -d login-validation-data.csv

      - name: Run API Tests - Get Booking ID
        run: newman run Restful-booker-collection.json --folder "Get booking id" -e restful-booker-env.json -d get-booking-id-validation-data.csv
